export const usersMock = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    status: 'active',
    avatar: 'avatar-1.png',
    job: 'Tech Recruiter',
    identifyLast6: '4.638-90',
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    status: 'active',
    avatar: 'avatar-2.png',
    job: 'Manager Recruiter',
    identifyLast6: '7.043-21',
  },
  {
    name: 'Alex Johnson',
    email: 'alex.johnson@example.com',
    status: 'active',
    avatar: 'avatar-3.png',
    job: 'Junir Recruiter',
    identifyLast6: '6.954-55',
  },
  {
    name: 'Emily Brown',
    email: 'emily.brown@example.com',
    status: 'active',
    avatar: 'avatar-4.png',
    job: 'Tech Recruiter',
    identifyLast6: '.626-55',
  },
  {
    name: 'Michael Wilson',
    email: 'michael.wilson@example.com',
    status: 'inactive',
    avatar: 'avatar-5.png',
    job: 'Manager Recruiter',
    identifyLast6: '2.672-11',
  },
  {
    name: 'Sarah Martinez',
    email: 'sarah.martinez@example.com',
    status: 'inactive',
    avatar: 'avatar-1.png',
    job: 'Manager Recruiter',
    identifyLast6: '2.318-45',
  },
  {
    name: 'David Garcia',
    email: 'david.garcia@example.com',
    status: 'active',
    avatar: 'avatar-2.png',
    job: 'Tech Recruiter',
    identifyLast6: '1.216-55',
  },
  {
    name: 'Jessica Taylor',
    email: 'jessica.taylor@example.com',
    status: 'active',
    avatar: 'avatar-3.png',
    job: 'Tech Recruiter',
    identifyLast6: '6.722-11',
  },
  {
    name: 'Christopher Brown',
    email: 'christopher.brown@example.com',
    status: 'active',
    avatar: 'avatar-4.png',
    job: 'Tech Recruiter',
    identifyLast6: '1.754-55',
  },
  {
    name: 'Amanda Rodriguez',
    email: 'amanda.rodriguez@example.com',
    status: 'active',
    avatar: 'avatar-5.png',
    job: 'Manager Recruiter',
    identifyLast6: '1.706-55',
  },
];
